sessional_management/sessional_management/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('sessional_marks.urls')),
]

sessional_management/sessional_marks/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^teacher_home', teacher_home, name='teacher_home'),
    url(r'^show', show, name='show'),
    url(r'^add_new', add_new, name='add_new'),
    url(r'^delete', delete, name='delete'),
    url(r'^teacher_registration',teacher_registration, name = 'teacher_registration')
    # url(r'^edit', edit, name='edit'),
    # url(r'^update', update, name='update'),
]

#     url(r'^Student_first_year$', display_Student_first_year, name="display_Student_first_year"),
#     url(r'^Student_second_year$', display_Student_second_year, name="display_Student_second_year"),
#     url(r'^Student_third_year$', display_Student_third_year, name="display_Student_third_year"),
#     url(r'^Student_fourth_year$', display_Student_fourth_year, name="display_Student_fourth_year"),


#     url(r'^add_Student_first_year$', add_Student_first_year, name="add_Student_first_year"),
#     url(r'^add_Student_second_year$', add_Student_second_year, name="add_Student_second_year"),
#     url(r'^add_Student_third_year$', add_Student_third_year, name="add_Student_third_year"),
#     url(r'^add_Student_four_year$', add_Student_fourth_year, name="add_Student_fourth_year"),
    
#     url(r'^Student_first_years/edit_item/(?P<pk>\d+)$', edit_Student_first_year, name="edit_Student_first_year"),
#     url(r'^Student_second_years/edit_item/(?P<pk>\d+)$', edit_Student_second_year, name="edit_Student_second_year"),
#     url(r'^Student_third_years/edit_item/(?P<pk>\d+)$', edit_Student_third_year, name="edit_Student_third_year"),
#     url(r'^Student_fourth_years/edit_item/(?P<pk>\d+)$', edit_Student_fourth_year, name="edit_Student_fourth_year"),
    

#     url(r'^Student_first_years/delete/(?P<pk>\d+)$', delete_Student_first_year, name="delete_Student_first_year"),
#     url(r'^Student_second_years/delete/(?P<pk>\d+)$', delete_Student_second_year, name="delete_Student_second_year"),
#     url(r'^Student_third_years/delete/(?P<pk>\d+)$', delete_Student_third_year, name="delete_Student_third_year"),
#     url(r'^Student_fourth_years/delete/(?P<pk>\d+)$', delete_Student_fourth_year, name="delete_Student_fourth_year"),
# ]

sessional_management/sessional_marks/models.py
from django.db import models
from sessional_marks.models import models
# Create your models here.

# data of first year student
class Student_table(models.Model):
    sstudent_name = models.CharField(max_length = 100)
    srollno = models.CharField(max_length = 12, blank = False)
    sbranch = models.CharField(max_length = 10)
    sfirst_marks = models.IntegerField()
    ssecond_marks = models.IntegerField()
    sthird_marks = models.IntegerField()
    stotal_marks = models.IntegerField()
    
    class Meta:
        abstract = True

    def __str__(self):
        return 'Rollno : {0} Branch : {1}'.format(self.srollno, self.sbranch)

    

class Student_first_year(Student_table):
    class Meta:
        db_table = "student_first_year"

class Student_second_year(Student_table):
    class Meta:
        db_table = "student_second_year"

class Student_third_year(Student_table):
    class Meta:
        db_table = "student_third_year"
    

class Student_fourth_year(Student_table):
    class Meta:
        db_table = "student_fourth_year"

class Teacher_data(models.Model):
    tteacher_name = models.CharField(max_length =20)
    tteacher_branch = models.CharField(max_length = 10)
    tteacher_email = models.EmailField(max_length = 100)
    tteacher_mob = models.CharField(max_length = 12)
    tteacher_userid = models.CharField(max_length = 20)
    tteacher_password = models.CharField(max_length = 10)

    class Meta:
        db_table = "Teacher_data"

    def __str__(self):
        return self.tteacher_name

sessional_management/sessional_marks/forms.py
from django import forms
from .models import *

class Student1Form(forms.ModelForm):
    class Meta:
        model = Student_first_year
        fields = "__all__"# ("sstudent_name", "srollno")

class Student2Form(forms.ModelForm):
    class Meta:
        model = Student_second_year
        fields = "__all__"

class Student3Form(forms.ModelForm):
    class Meta:
        model = Student_third_year
        fields = "__all__"

class Student4Form(forms.ModelForm):
    class Meta:
        model = Student_fourth_year
        fields = "__all__"

class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher_data
        fields = "__all__"

sessional_management/sessional_marks/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *


# Create your views here.
def add_new(request):
    if request.method == "POST":
        form = Student1Form(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("/show/")
            except:
                pass
    else:
        form = Student1Form()
    return render(request,"display/new_student.html",{'form':form})


def teacher_sign_in(request):
    if request.method == "POST":
        return render(request,"/teacher_home")

def teacher_home(request):
    teacher_record = Teacher_data.objects.all()
    return render(request,"display/teacher_home.html",{'teacher_record':teacher_record})

def index(request):
    return render(request,"display/index.html")

def teacher_registration(request):
    if request.method == "POST":
        form = TeacherForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("/teacher_home/")
            except:
                pass
    else:
        form = TeacherForm()
    return render(request,"display/teacher_registration.html",{'form':form})   

def show(request):
    student_first_record = Student_first_year.objects.all()
    return render(request,"display/show.html",{'student_record':student_first_record})

def delete(request, id):
    student_record = Student_first_year.objects.get(id = id)
    student_record.delete()
    return redirect("/show/")


# def edit(request, id):
#     student_record = Student_first_year.objects.get(id = id)
#     return render(request,"display/edit.html",{'student_record':student_record})

# def update(request, id):
#     student_record = Student_first_year.objects.get(id = id)
#     form = Student1Form(request.POST, instance = student_record)
#     if form.is_valid:
#         form.save()
#         return redirect("/show/")

#     return render(request,"display/edit.html",{'student_record':student_record})






#----------------------------------------------------------------------------------------------------------------

"""

def index(request):
    return HttpResponseRedirect(reverse('employee_list'))

def user_login(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            if request.GET.get('next', None):
                return HttpResponseRedirect(request.GET['next'])
            return HttpResponseRedirect(reverse('employee_list'))
        else:
            context["error"] = "Provide valid credentials !!"
            return render(request, "auth/login.html", context)
    else:
        return render(request, "auth/login.html", context)

@login_required(login_url="/login/")
def success(request):
    context = {}
    context['user'] = request.user
    return render(request, "auth/success.html", context)

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('user_login'))



"""

sessional_management/templates/display/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}
            hiii
            {% endblock %}
        </title>
    </head>
    <body>
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </body>
</html>

sessional_management/templates/display/edit.html
<!DOCTYPE html>
{%load staticfiles%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>edit</title>
    <link rel="stylesheet" href="{%static "displayingcss/edit_css.css"%}">
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h1>Sessional Management</h1>
      </div>
      <br>
      <div class="back_edit_page">
        <h1>Edit Student Data</h1>
        <hr>
        <div class="edit_block">
          <form class="form_part" action="/update/{{student_record.id}}" method="post">
            {% csrf_token %}
           <tr>
              <td>Student Name : </td><br>
              <td><input type="text" id="id_sstudent_name" name="sstudent_name" value="{{student_record.sstudent_name}}" maxlength="100" required></td>

             <br><br>

            <tr>
              <td>Student Roll no : </td><br>
              <td><input type="text" id="id_srollno" name="srollno" value="{{student_record.srollno}}" maxlength="12" required></td>
            </tr>
              <br> <br>

            <tr>
              <td>Student Branch : </td><br>
              <td><input type="text" id="id_sbranch" name="sbranch" value="{{student_record.sbranch}}" maxlength="20" required></td>
            </tr>
              <br> <br>

            <tr>
              <td>Sessional First : </td><br>
              <td><input type="number" id="id_sfirst_marks" name="sfirst_marks" value="{{student_record.sfirst_marks}}" maxlength="2" required></td>
            </tr>
              <br> <br>

            <tr>
              <td>Sessional Second  : </td><br>
              <td><input type="number" id="id_ssecond_marks" name="ssecond_marks" value="{{student_record.ssecond_marks}}" maxlength="2" required></td>
            </tr>
              <br> <br>

            <tr>
              <td>Sessional Third : <br>
              <td><input type="number" id="id_sthird_marks" name="sthird_marks" value="{{student_record.sthird_marks}}" maxlength="2" required></td>
            </tr>
              <br> <br>

            <tr>
              <td>Total : </td><br>
              <td><input type="number" id="id_stotal_marks" name="stotal_mraks" value="{{student_record.stotal_marks}}" maxlength="2" required></td>
            </tr>
              <br> <br>

            <tr>
              <td><button type="submit" name="submit_button">update</button></td>&nbsp&nbsp&nbsp&nbsp&nbsp
              <td><button type="reset" name="reset_button">reset</button></td>
            </tr>
            <br> <br>
          </form>
        </div>
      </div>
      <div class="footer">

      </div>
    </div>
    <br>
  </body>
</html>

sessional_management/templates/display/index.html
<!DOCTYPE html>
{%load staticfiles%}
<html>
<head>
	<title>sign in</title>
	<link rel="stylesheet" type="text/css" href="{%static "displayingcss/teacher_login.css"%}">
	<!--<script type="text/javascript">
		function sure() {
			// body...
			//alert("are you sure !!!")
		}
	</script>-->
	
</head>
<body>
	<div class="container">
	<form method="post" action="/teacher_home">
	
		<div class="container1">
				{% csrf_token %}
			<div class="head">
				<h1>SESSIONAL MANAGEMENT</h1>	
			</div>
			<div class="mainpart">
				<tr><b>&nbsp&nbsp&nbsp&nbsp&nbsp Username: </b> <input type="Username" name="user_name"  placeholder="username" maxlength="50" required="">
				</tr><br><br>
				<tr><b>&nbsp&nbsp&nbsp&nbsp&nbsp Password : </b><input type="pass" name="teach_pass" required="" placeholder="password">
				</tr><br><br>
				<tr>
					<td>Dept :&nbsp&nbsp&nbsp&nbsp&nbsp <select name="dept" width=50><option>cse</option></select></td>
				</tr><br><br>
				<tr >
					&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<input type="submit" value="submit" onclick="sure()" style="width: 100px;">&nbsp&nbsp&nbsp&nbsp<input type="reset" style="width: 100px;">
				</tr>
				</div>	
				<hr>
				<h5><a href="/teacher_registration">click here for new registration</a></h5>
			</div>
	</form>
	</div>
</body>
</html>

sessional_management/templates/display/new_student.html
<!DOCTYPE html>
{%load staticfiles%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>new student</title>
    <link rel="stylesheet" href="{%static "displayingcss/new_student.css"%}">
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h1>Sessional Management</h1>
      </div>
      <br>
      <div class="back_edit_page">
        <h1>Add new Student</h1>
        <hr>
        <div class="edit_block">
          <form class="form_part" action="/add_new/" method="post">
            {% csrf_token %}
            <tr>
              <td>Student Name : </td><br>
              <td>{{form.sstudent_name}}</td>
            </tr>
             <br><br>

            <tr>
              <td>Student Roll no : </td><br>
              <td>{{form.srollno}}</td>
            </tr>
              <br> <br>

            <tr>
              <td>Student Branch : </td><br>
              <td>{{form.sbranch}}</td>
            </tr>
              <br> <br>

            <tr>
              <td>Sessional First : </td><br>
              <td>{{form.sfirst_marks}}</td>
            </tr>
              <br> <br>

            <tr>
              <td>Sessional Second  : </td><br>
              <td>{{form.ssecond_marks}}</td>
            </tr>
              <br> <br>

            <tr>
              <td>Sessional Third : <br>
              <td>{{form.sthird_marks}}</td>
            </tr>
              <br> <br>

            <tr>
              <td>Total : </td><br>
              <td>{{form.stotal_marks}}</td>
            </tr>
              <br> <br>

            <tr>
              <td><button type="submit" name="submit_button">submit</button></td>&nbsp&nbsp&nbsp&nbsp&nbsp
              <td><button type="reset" name="reset_button">reset</button></td>
            </tr>
            <br> <br>
          </form>
        </div>
      </div>
      <div class="footer">

      </div>
    </div>
    <br>
  </body>
</html>

sessional_management/templates/display/show.html
<!DOCTYPE html>
{% load staticfiles%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{%static "displayingcss/show_css.css" %}">
    <title>show</title>
  </head>
  <body>
      <div class="container">
        <div class="header">
          <h1>Sessional Management</h1>
        </div>
        <br>
          <div class="show_table">
            {% if student_record %}
            <table>
              <caption><h1>STUDENT DATA </h1></caption>
              <thead>
                <th>Student Name</th>
                <th>Roll NO</th>
                <th>Branch</th>
                <th>First Sessional marks</th>
                <th>Second Sessional marks</th>
                <th>Third Sessional marks</th>
                <th>total</th>
                <th colspan="2">action</th>
              </thead>
              {%for stdnt in student_record%}
              <tr>
                <td>{{stdnt.sstudent_name}}</td>
                <td>{{stdnt.srollno}}</td>
                <td>{{stdnt.sbranch}}</td>
                <td>{{stdnt.sfirst_marks}}</td>
                <td>{{stdnt.ssecond_marks}}</td>
                <td>{{stdnt.sthird_marks}}</td>
                <td>{{stdnt.stotal_marks}}</td>

                <!-- <td>
                   <a href="/edit/{{stdnt.id}}"><span>Edit</span></a>
                </td> -->
                <td>
                  <a href="/delete/{{stdnt.id}}"><span>Delete</span></a>
                </td>
              </tr>
              {% endfor %}
            </table>
            {% else %}
            <p>no record found !!!</p>
            {% endif %}
            <br>

            <div class="footer">
              <a href="/add_new"><h5>add new Student</h5></a>
            </div>
          </div>
          <div class="footer">

          </div>
      </div>
  </body>
</html>

sessional_management/templates/display/teacher_home.html
<!DOCTYPE html>
{%load staticfiles%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>home page</title>
    <link rel="stylesheet" href="{%static "displayingcss/teacher_login_home.css"%}" type="text/css">
  </head>
  <body>
    <div class="main_container">
      <div class="header">
        <h1>Sessional Management</h1>
      </div>

      <div class="container2">
      {% if teacher_record %}
        <h1>Admin Page</h1>
        <br>
        <hr>
        <br><br>
        {% for td in teacher_record %}
        <div class="leftdiv">
            
          <p>Name : &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{td.tteacher_name}}</p><br>
          <p>Branch : &nbsp&nbsp&nbsp&nbsp&nbsp{{td.tteacher_branch}}</p><br>
        </div>
        <div class="rightdiv">
          <p>Id no : &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{steacher_id}}</p><br>
          <p>session : &nbsp&nbsp&nbsp&nbsp&nbsp{{syear_session}}</p><br>
        </div>
         {% endfor %} 
        <br><br>
      {% else %}
        <p>no data</p>
        {% endif %}
        <br>
        <h4>Search Student Data</h4>
        <hr>
        <br>
        <form class="" action="/show" method="post">
          {% csrf_token %}
          <div class="search_container">
            <tr>

              <td>year :</td>&nbsp&nbsp&nbsp&nbsp&nbsp
              &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
              <td> <select class="" name="syear">
                <option value="first">first</option>
                <option value="second">second</option>
                <option value="third">third</option>
                <option value="fourth">fourth</option>
              </select> </td>
              &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
              &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
              &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp


              <td>Branch  :</td>&nbsp&nbsp&nbsp&nbsp&nbsp
              <td>
            <select class="" name="sbranch">
              <option value="cse">Computer Science anad Engineering</option>
              <!-- <option value="me">Mechanical Engineering</option>
              <option value="ece">Electronics and Communication Engineering</option> -->
            </select>
          </td>
            </tr>
            <br><br>
            <tr>


              <td>semester :</td>&nbsp&nbsp&nbsp&nbsp&nbsp
              <td> <select class="" name="ssem" >
                <option value="first" selected>first</option>
                <option value="second">second</option>
                <option value="third">third</option>
                <option value="fourth">fourth</option>
                <option value="fifth">fifth</option>
                <option value="sixt">sixth</option>
                <option value="seventh">seventh</option>
                <option value="eighth">eighth</option>
              </select> </td>
              &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
              &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
              &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp


              <td>Subject  :</td>&nbsp&nbsp&nbsp&nbsp&nbsp
              <td>
            <select class="" name="ssubject">
              <option value="ds" selected>Data Structure using C</option>
              <option value="dbms">Database Managemet System</option>
              <option value="ppl">principal of programming language</option>
            </select>
          </td>
            </tr>
            <br><br>
            <tr>
              <td> <button type="submit" name="search_data" >search</button></td>
              <td> <button type="reset" >reset</button></td>
            </tr>
            <br><br>
          </div>
        </form>
        <br>
      </div>
        
    </div>
  </body>
</html>

sessional_management/templates/display/teacher_registration.html
<html>
	<head>
		<title>form</title>
		<style>
			#vid{
				min-height: 200px;
				width: 960px;
				background: gray;
				margin: auto;
			}
			body{
				font-family: cursive;
				font-size: 20px;
				color: white;
			}
		</style>
	</head>
	<body>
		<div id="vid">
			<form method="post" action="/teacher_registration/">
				{% csrf_token %}
				<fieldset>
					<legend>registration form</legend>
					
					<tr>
					  <td>Teacher Name : </td><br>
					  <td>{{form.tteacher_name}}</td>
					</tr>
					 <br><br>
		
					<tr>
					  <td>Branch</td><br>
					  <td>{{form.tteacher_branch}}</td>
					</tr>
					  <br> <br>
		
					<tr>
					  <td>Email : </td><br>
					  <td>{{form.tteacher_email}}</td>
					</tr>
					  <br> <br>
		
					<tr>
					  <td>Mobile :</td><br>
					  <td>{{form.tteacher_mob}}</td>
					</tr>
					  <br> <br>
		
					<!-- <tr>
					  <td>Course : </td> </td><br>
					  <td>{{form.tteacher_course}}</td>
					</tr>
					  <br> <br> -->
					  <tr>
							<td>User :</td><br>
							<td>{{form.tteacher_userid}}</td>
						  </tr>
							<br> <br>
		
					<tr>
					  <td>Password : </td><br>
					  <td>{{form.tteacher_password}}</td>
					</tr>
					<br><br>
					<tr><td><input type="submit" value="submit"></td>&nbsp;&nbsp;&nbsp;<td style="margin-left: 0px;"><input type="reset"> </td>
					</tr>
				</fieldset>
			</form>
		</div>
		
	</body>
</html>